### ISSUE TITLE
mbed-cli --build-profiles extended to build directories

### ISSUE THREAD

**Issue by mbartling** [ARMmbed/ref-wem-firmware#35]
When building with mbed-cli 1.8.1, build profiles are appended to the target build directory names. For example, `./BUILD/UBLOX_EVK_ODIN_W2/GCC_ARM/` becomes `./BUILD/UBLOX_EVK_ODIN_W2/GCC_ARM-RELEASE/`. Note this affects both bootloader build and app build. 

Hacky example fix (Makefile):
```Makefile
MBED_TOOLCHAIN_EXTENSION=$(shell basename ${BUILD_PROFILE} .json)
BOOTLDR_TOOLCHAIN_EXTENSION=$(shell basename ${BOOTLOADER_BUILD_PROFILE} .json)`
MBED_BUILD_DIR:=./BUILD/${MBED_TARGET}/${MBED_TOOLCHAIN}-${MBED_TOOLCHAIN_EXTENSION}
BOOTLDR_BUILD_DIR:=./BUILD/${MBED_TARGET}/${MBED_TOOLCHAIN}-${BOOTLDR_TOOLCHAIN_EXTENSION}
```

This only impacts the copying of binaries from respective build dirs to `./bin`.

**Comment by costanic** [comment]
Thanks for the report and the suggested fix.  We'll investigate upgrading the supported version of mbed-cli from 1.2.2, as listed in requirements.txt, since 1.2.2 seems to be pretty old.

**Comment by mbanders** [comment]
Alright, made a pull request and it compiles for me, producing the desired bin and hex files: https://github.com/ARMmbed/ref-wem-firmware/pull/36

**Comment by mbanders** [comment]
Fixed.
